name: VNDB quotes
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run job
        run: python main.py
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
